"""empty message

Revision ID: a5b1bb4d5fe9
Revises: 
Create Date: 2021-02-02 14:23:10.746663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b1bb4d5fe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yourName', sa.String(length=50), nullable=False),
    sa.Column('yourEmailAddress', sa.String(length=255), nullable=False),
    sa.Column('contactPhone', sa.Integer(), nullable=False),
    sa.Column('yourProfession', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
