"""empty message

Revision ID: ec096e478e90
Revises: a5b1bb4d5fe9
Create Date: 2021-02-02 16:06:16.050131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec096e478e90'
down_revision = 'a5b1bb4d5fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('request', sa.Text(), nullable=False))
    op.alter_column('user', 'contactPhone',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('user', 'yourEmailAddress',
               existing_type=sa.VARCHAR(length=255),
               nullable='False')
    op.alter_column('user', 'yourName',
               existing_type=sa.VARCHAR(length=50),
               nullable='False')
    op.alter_column('user', 'yourProfession',
               existing_type=sa.VARCHAR(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'yourProfession',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'yourName',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'yourEmailAddress',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'contactPhone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'request')
    # ### end Alembic commands ###
